# - Numpy
### 1. Installation et chargement de Numpy 

In [3]:
!pip install numpy
import numpy as np

### 2. Creation des données (ou tableau) avec numpy

#### 2.1 Créer un numpy array avec une liste/lise de liste (matrice)

In [13]:
# Creation à partir d'une liste
liste=[1,2, 3, 4, 5] # definition de la liste
array_with_liste = np.array(liste)
print(array_with_liste)

[1 2 3 4 5]


### Creation à partir d'une matrice

In [17]:
# Creation d'un numpy array à partir d'une liste de listes (matrices)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2.2 Creer un numpy array à partir des fonctions intégrées

In [21]:
# Creer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Creer un numpy array a a partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
# Creer un numpy arry avec la fonction eye
array_eye = np.eye(6) # pour creer la matrice identité de dimension 6
array_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
# Creer un numpay array avec la fonction arange: pour creer des nombres entre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2) # 2 etant le pas 
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [37]:
# Creer un numpy array avec la fonction linspace # generer une sequence de nombre entre deux valeurs données
# avec un nombre de points  données
array_linspace = np.linspace(0, 1, 5) # tres utile pour les graphiques
array_linspace # Creer des points equidistants entre 0 et 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
# Creer un numpy array de valeurs aléatoires avec la fonction random
array_random =np.random.random((4,3)) # utile pour initialiser les poids dans les reseaux de neurones, génerer des données
print(array_random) # me geere un tableau de données de 4 lignes et 3 colonnes
# si c'est un vecteur de talle taille  3, On aura (3) , une matrice de taille 2x2, on aura (2,2)

[[0.84191836 0.55851081 0.23637749]
 [0.83299482 0.8582512  0.28096214]
 [0.97244011 0.08524444 0.70554034]
 [0.60477313 0.70218439 0.91513696]]


### 3 Fonctions mathématiques et statistiques avec numpy

In [ ]:
# Fonctions mathématiques basiques
arrayl= array_wise_liste
array_sum = np.sum(arrayl)
array_mean = np.mean(arrayl)
array_std = np.std(arrayl)
array_min = np.min(arrayl)
array_max = np.max(arrayl)
array_sqrt = np.sqrt(arrayl)
array_abs =np.abs(arrayl)
array_power = np.power(arrayl)
array_exp = np.exp(arrayl)
array_log = np.log(arrayl)
array_sin = np.sin(arrayl)
array_median = np.median(arrayl)
array_sum

### 4 Manipulation des matrices avec Numpy

In [49]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [51]:
# Transposée
transpose = np.transpose(array_with_matrice)
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [55]:
# Inversion (pour les matrices carrées non singulieres)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-0. -0. -0.  1. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [59]:
# Detreminant
determinant = np.linalg.det(array_eye)
print(determinant)

1.0


### 4 Acceder aux elements, selectionner, modifier et mettre à jour un numpy array

In [64]:
# Acces aux elements
arrayl = np.array([1,2,3,4,5])
premier_element = arrayl[0]
print(premier_element)
# pour accerder au dernier element, ce sera arrayl[-1]

1


In [68]:
# Modification d'un element
arrayl[0] = 10
print(arrayl)

[10  2  3  4  5]


In [78]:
# Selection des elements qui respectent une condition
condition = arrayl > 5
elements_respectant_condition = arrayl[condition]
elements_respectant_condition

array([10])

In [84]:
condition = arrayl > 3
condition
indices = np.where(arrayl > 3) # revoie les indices des elements superieurs à 3
indices

(array([0, 3, 4], dtype=int64),)

In [86]:
arrayl > 3

array([ True, False, False,  True,  True])

In [92]:
# Utilisation de np.where qui permet de faire des filtres
indices = np.where(arrayl > 5)
elements_respectant_condition_np_where = arrayl[indices]
print(elements_respectant_condition_np_where)

[10]


In [96]:
# Mise à jour d'un numpy array
arrayl[condition]=0 # avec condition = arrayl > 3 , permet donc de remplacer par des 0 tous les elements > 3
print(arrayl)

[0 2 3 0 0]


In [102]:
# Slicing et indexaction avncée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :] # pour recuperer la premiere ligne (indice 0)
premiere_ligne

array([1, 2, 3])

In [104]:
# prepiere colonne
premiere_colonne = array6[:,0]
premiere_colonne

array([1, 4, 7])

In [108]:
# Sous matrice
sous_matrice = array6[1:3,1:3] # [1:3] pour les lignes prend 1 à 2 uniquement, et pour les colonnes prend 2 à 3 uniquement
sous_matrice

array([[5, 6],
       [8, 9]])

In [110]:
# Indexation avancée
lignes = [0, 1] #  toutjours decaler de 1 pour identifier les valeurs
colonnes =[1, 2] # declaler egalement de 1
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [112]:
# Operations elementaires et diffusion (broacasting)
array7 =np.array([1,2,3])
array8 = np.array([4, 5, 6])

# Addition elementaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [116]:
# Multiplication elementaire
array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [118]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9 + array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

### 6 Redimensionnement, append, type de données taille etc

In [121]:
# r redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [125]:
# Ajouter des elemnts dans un numpy array
arrayl_allonge = np.append(arrayl, [6, 7, 8])
print(arrayl_allonge)

[0 2 3 0 0 6 7 8]


In [128]:
# Connaitre les caracteristiques d'un numpy array
array_with_matrice.shape # dimension de l'array

(3, 3)

In [132]:
# connaitre le type d'objet
type(array_with_matrice) # type de l'objet

numpy.ndarray

In [134]:
# Connaitre le type des él
arrayl.dtype # type des objets

dtype('int32')

In [136]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')

# - Panda
### commprendre Panda (manipulation des données,permet de faire les statistiques classique)
#### 1. Installation et chargement

In [142]:
# Installation de pandas
!pip install pandas
import pandas as pd

#### 2. Creation des dataframe avec pandas

In [146]:
# Creation du dictionnaire
etudiant = {"Nom":["X", "Y", "Z"],"Prenom":["x","y","z"],"Notes":[1,2,3]}
etudiant

{'Nom': ['X', 'Y', 'Z'], 'Prenom': ['x', 'y', 'z'], 'Notes': [1, 2, 3]}

In [150]:
# Transformer le dictionnaire en dataframe
df_etudiant=pd.DataFrame(etudiant)
df_etudiant

Nom Prenom  Notes
0   X      x      1
1   Y      y      2
2   Z      z      3

#### Changer le chemin d'acces (important à connaitre)

In [165]:
import os
os.chdir('C:/Users/brech/Downloads')

In [167]:
# Creation à partir d'un fichier csv/excel
df= pd.read_csv("credit_risk_dataset.csv",sep=";")
df

Id_personne  Age       Nom     Prenom  Revenu Type de domicile  \
0             1   40     Akono     Nathan   59000        Locataire   
1             2   35      Akwa      Aicha   70000     Propriétaire   
2             3   25    Arnaud      Matin    9600        Locataire   
3             4   23       Awa      Marie   44000             Pret   
4             5   24    Dubois   Lachaise   54400             Pret   
5             6   21    Durand     Bertin    9900        Locataire   
6             7   44   Ekounou        Eli   77100     Propriétaire   
7             8   24   Mendong       Zibi   33000        Locataire   
8             9   24    Moussa     Hamado   24000        Locataire   
9            10   50  Mvog-ada     Bertin   80000     Propriétaire   
10           11   22     Mvogo    Melanie   25000        Locataire   
11           12   21      Neba   Charlène   10000        Locataire   
12           13   34       Ngo  Stephanie   95000             Pret   
13           14   26     Ngono      Marie  108160             Pret   
14           15   23      Omar    Mohamed  115000             Pret   
15           16   32     Petit     Prince  500000     Propriétaire   
16           17   23   Richard     Arnaud  120000        Locataire   
17           18   31    Tchana     Albert   92111        Locataire   
18           19   23  Tchuente       Isis  113000        Locataire   
19           20   24     Yemba     Elodie   10800             Pret   

           Travail Grade du pret  Montant du prêt  Taux_interet  \
0              CDI             D            35000         16.02   
1              CDI             B             1000         11.14   
2              CDD             C             5500         12.87   
3              CDI             C            35000         15.23   
4              CDI             C            35000         14.27   
5              CDD             A             2500          7.14   
6              CDI             B            35000         12.42   
7              CDI             B            35000         11.11   
8              CDI             A            35000          8.90   
9              CDI             D             1600         14.74   
10             CDD             B            35000         10.37   
11             CDD             A             4500          8.63   
12             CDI             A            35000          7.90   
13             CDI             E            35000         18.39   
14  Entreprenariat             A            35000          7.90   
15  Entreprenariat             B            30000         10.65   
16             CDI             A            35000          7.90   
17             CDD             F            35000         20.25   
18  Entreprenariat             D            35000         18.25   
19             CDD             B             1750         10.99   

    Statut_du_pret  Taux_endettement Défaut  Nombre de credit historique  
0                1              0.59      Y                            3  
1                0              0.10      N                            2  
2                1              0.57      N                            3  
3                1              0.53      N                            2  
4                1              0.55      Y                            4  
5                1              0.25      N                            2  
6                1              0.45      N                            3  
7                1              0.44      N                            4  
8                1              0.42      N                            2  
9                1              0.16      N                            3  
10               1              0.41      N                            4  
11               1              0.45      N                            2  
12               1              0.37      N                            2  
13               1              0.32      N                            4  


In [175]:
# Importation d'un fichier excel
df= pd.read_excel("credit_dataset_excel.xlsx")
df

Id_personne  Age       Nom     Prenom  Revenu Type de domicile  \
0             1   40     Akono     Nathan   59000        Locataire   
1             2   35      Akwa      Aicha   70000     Propriétaire   
2             3   25    Arnaud      Matin    9600        Locataire   
3             4   23       Awa      Marie   44000             Pret   
4             5   24    Dubois   Lachaise   54400             Pret   
5             6   21    Durand     Bertin    9900        Locataire   
6             7   44   Ekounou        Eli   77100     Propriétaire   
7             8   24   Mendong       Zibi   33000        Locataire   
8             9   24    Moussa     Hamado   24000        Locataire   
9            10   50  Mvog-ada     Bertin   80000     Propriétaire   
10           11   22     Mvogo    Melanie   25000        Locataire   
11           12   21      Neba   Charlène   10000        Locataire   
12           13   34       Ngo  Stephanie   95000             Pret   
13           14   26     Ngono      Marie  108160             Pret   
14           15   23      Omar    Mohamed  115000             Pret   
15           16   32     Petit     Prince  500000     Propriétaire   
16           17   23   Richard     Arnaud  120000        Locataire   
17           18   31    Tchana     Albert   92111        Locataire   
18           19   23  Tchuente       Isis  113000        Locataire   
19           20   24     Yemba     Elodie   10800             Pret   

           Travail Grade du pret  Montant du prêt  Taux_interet  \
0              CDI             D            35000         16.02   
1              CDI             B             1000         11.14   
2              CDD             C             5500         12.87   
3              CDI             C            35000         15.23   
4              CDI             C            35000         14.27   
5              CDD             A             2500          7.14   
6              CDI             B            35000         12.42   
7              CDI             B            35000         11.11   
8              CDI             A            35000          8.90   
9              CDI             D             1600         14.74   
10             CDD             B            35000         10.37   
11             CDD             A             4500          8.63   
12             CDI             A            35000          7.90   
13             CDI             E            35000         18.39   
14  Entreprenariat             A            35000          7.90   
15  Entreprenariat             B            30000         10.65   
16             CDI             A            35000          7.90   
17             CDD             F            35000         20.25   
18  Entreprenariat             D            35000         18.25   
19             CDD             B             1750         10.99   

    Statut_du_pret  Taux_endettement Défaut  Nombre de credit historique  
0                1              0.59      Y                            3  
1                0              0.10      N                            2  
2                1              0.57      N                            3  
3                1              0.53      N                            2  
4                1              0.55      Y                            4  
5                1              0.25      N                            2  
6                1              0.45      N                            3  
7                1              0.44      N                            4  
8                1              0.42      N                            2  
9                1              0.16      N                            3  
10               1              0.41      N                            4  
11               1              0.45      N                            2  
12               1              0.37      N                            2  
13               1              0.32      N                            4  


In [177]:
# Afficher les 5 premiers elemnts
df.head(5)

Id_personne  Age     Nom    Prenom  Revenu Type de domicile Travail  \
0            1   40   Akono    Nathan   59000        Locataire     CDI   
1            2   35    Akwa     Aicha   70000     Propriétaire     CDI   
2            3   25  Arnaud     Matin    9600        Locataire     CDD   
3            4   23     Awa     Marie   44000             Pret     CDI   
4            5   24  Dubois  Lachaise   54400             Pret     CDI   

  Grade du pret  Montant du prêt  Taux_interet  Statut_du_pret  \
0             D            35000         16.02               1   
1             B             1000         11.14               0   
2             C             5500         12.87               1   
3             C            35000         15.23               1   
4             C            35000         14.27               1   

   Taux_endettement Défaut  Nombre de credit historique  
0              0.59      Y                            3  
1              0.10      N                            2  
2              0.57      N                            3  
3              0.53      N                            2  
4              0.55      Y                            4

In [179]:
# affichage des 5 derniers elemnts
df.tail(5)

Id_personne  Age       Nom  Prenom  Revenu Type de domicile  \
15           16   32     Petit  Prince  500000     Propriétaire   
16           17   23   Richard  Arnaud  120000        Locataire   
17           18   31    Tchana  Albert   92111        Locataire   
18           19   23  Tchuente    Isis  113000        Locataire   
19           20   24     Yemba  Elodie   10800             Pret   

           Travail Grade du pret  Montant du prêt  Taux_interet  \
15  Entreprenariat             B            30000         10.65   
16             CDI             A            35000          7.90   
17             CDD             F            35000         20.25   
18  Entreprenariat             D            35000         18.25   
19             CDD             B             1750         10.99   

    Statut_du_pret  Taux_endettement Défaut  Nombre de credit historique  
15               0              0.06      N                            3  
16               0              0.29      N                            4  
17               1              0.32      N                            4  
18               1              0.31      N                            4  
19               1              0.16      N                            2

In [181]:
# Voir la liste des colonnes du tableau dataframe
df.columns

Index(['Id_personne', 'Age', 'Nom', 'Prenom', 'Revenu', 'Type de domicile',
       'Travail', 'Grade du pret', 'Montant du prêt', 'Taux_interet',
       'Statut_du_pret', 'Taux_endettement', 'Défaut',
       'Nombre de credit historique'],
      dtype='object')

In [185]:
# Voir le type de données de ma base de données
df.dtypes

Id_personne                      int64
Age                              int64
Nom                             object
Prenom                          object
Revenu                           int64
Type de domicile                object
Travail                         object
Grade du pret                   object
Montant du prêt                  int64
Taux_interet                   float64
Statut_du_pret                   int64
Taux_endettement               float64
Défaut                          object
Nombre de credit historique      int64
dtype: object

In [187]:
# Voir la dimension du tableau
df.shape

(20, 14)

### 3. Lecture des tableaux pandas
#### 3.1 Selctionner des colonnes

In [192]:
# Si la variable n'a pas d'espace
df.Id_personne.head(5)

0    1
1    2
2    3
3    4
4    5
Name: Id_personne, dtype: int64

In [196]:
# Si la variable a des caracteres speciaux
df['Type de domicile'].head(5)

0       Locataire
1    Propriétaire
2       Locataire
3            Pret
4            Pret
Name: Type de domicile, dtype: object

In [198]:
# Selectionner plusieurs colonnes
new_df=df[['Type de domicile','Nom']]
new_df.head(5)

Type de domicile     Nom
0        Locataire   Akono
1     Propriétaire    Akwa
2        Locataire  Arnaud
3             Pret     Awa
4             Pret  Dubois

In [202]:
# Connaitre les valeurs uniques d'une variable
df['Type de domicile'].unique()

array(['Locataire', 'Propriétaire', 'Pret'], dtype=object)

In [214]:
# Selectionner les lignes qui respectent une condition uniuement
new_cdi = df[df['Travail']=='CDI']
new_cdi.head(5)

Id_personne  Age      Nom    Prenom  Revenu Type de domicile Travail  \
0            1   40    Akono    Nathan   59000        Locataire     CDI   
1            2   35     Akwa     Aicha   70000     Propriétaire     CDI   
3            4   23      Awa     Marie   44000             Pret     CDI   
4            5   24   Dubois  Lachaise   54400             Pret     CDI   
6            7   44  Ekounou       Eli   77100     Propriétaire     CDI   

  Grade du pret  Montant du prêt  Taux_interet  Statut_du_pret  \
0             D            35000         16.02               1   
1             B             1000         11.14               0   
3             C            35000         15.23               1   
4             C            35000         14.27               1   
6             B            35000         12.42               1   

   Taux_endettement Défaut  Nombre de credit historique  
0              0.59      Y                            3  
1              0.10      N                            2  
3              0.53      N                            2  
4              0.55      Y                            4  
6              0.45      N                            3

In [216]:
# Selectionner les lignes avec plusieurs conditions
new_cdi_d = df[(df['Travail']=='CDI') & (df['Grade du pret']=='D') ]
new_cdi_d.head(5)


Id_personne  Age       Nom  Prenom  Revenu Type de domicile Travail  \
0            1   40     Akono  Nathan   59000        Locataire     CDI   
9           10   50  Mvog-ada  Bertin   80000     Propriétaire     CDI   

  Grade du pret  Montant du prêt  Taux_interet  Statut_du_pret  \
0             D            35000         16.02               1   
9             D             1600         14.74               1   

   Taux_endettement Défaut  Nombre de credit historique  
0              0.59      Y                            3  
9              0.16      N                            3

### 3.3 Indexaction avec iloc (index location)

In [219]:
# selection de la premiere ligne
df.iloc[0]

Id_personne                            1
Age                                   40
Nom                                Akono
Prenom                            Nathan
Revenu                             59000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          D
Montant du prêt                    35000
Taux_interet                       16.02
Statut_du_pret                         1
Taux_endettement                    0.59
Défaut                                 Y
Nombre de credit historique            3
Name: 0, dtype: object

In [221]:
# Selection de la derniere ligne 
df.iloc[-1]

Id_personne                        20
Age                                24
Nom                             Yemba
Prenom                         Elodie
Revenu                          10800
Type de domicile                 Pret
Travail                           CDD
Grade du pret                       B
Montant du prêt                  1750
Taux_interet                    10.99
Statut_du_pret                      1
Taux_endettement                 0.16
Défaut                              N
Nombre de credit historique         2
Name: 19, dtype: object

In [225]:
# Selctionner les deux premieres lignes et les deux premieres colonnes
df.iloc[0:2,0:2]

Id_personne  Age
0            1   40
1            2   35

#### 3.4 Indexation avec loc (acceder aux elements à partir des label)

In [228]:
# Creation d'un index dans le dataframe df_etudiant
# On veut que le nom devienne index
df = df.set_index("Nom")
df

Id_personne  Age     Prenom  Revenu Type de domicile  \
Nom                                                              
Akono               1   40     Nathan   59000        Locataire   
Akwa                2   35      Aicha   70000     Propriétaire   
Arnaud              3   25      Matin    9600        Locataire   
Awa                 4   23      Marie   44000             Pret   
Dubois              5   24   Lachaise   54400             Pret   
Durand              6   21     Bertin    9900        Locataire   
Ekounou             7   44        Eli   77100     Propriétaire   
Mendong             8   24       Zibi   33000        Locataire   
Moussa              9   24     Hamado   24000        Locataire   
Mvog-ada           10   50     Bertin   80000     Propriétaire   
Mvogo              11   22    Melanie   25000        Locataire   
Neba               12   21   Charlène   10000        Locataire   
Ngo                13   34  Stephanie   95000             Pret   
Ngono              14   26      Marie  108160             Pret   
Omar               15   23    Mohamed  115000             Pret   
Petit              16   32     Prince  500000     Propriétaire   
Richard            17   23     Arnaud  120000        Locataire   
Tchana             18   31     Albert   92111        Locataire   
Tchuente           19   23       Isis  113000        Locataire   
Yemba              20   24     Elodie   10800             Pret   

                 Travail Grade du pret  Montant du prêt  Taux_interet  \
Nom                                                                     
Akono                CDI             D            35000         16.02   
Akwa                 CDI             B             1000         11.14   
Arnaud               CDD             C             5500         12.87   
Awa                  CDI             C            35000         15.23   
Dubois               CDI             C            35000         14.27   
Durand               CDD             A             2500          7.14   
Ekounou              CDI             B            35000         12.42   
Mendong              CDI             B            35000         11.11   
Moussa               CDI             A            35000          8.90   
Mvog-ada             CDI             D             1600         14.74   
Mvogo                CDD             B            35000         10.37   
Neba                 CDD             A             4500          8.63   
Ngo                  CDI             A            35000          7.90   
Ngono                CDI             E            35000         18.39   
Omar      Entreprenariat             A            35000          7.90   
Petit     Entreprenariat             B            30000         10.65   
Richard              CDI             A            35000          7.90   
Tchana               CDD             F            35000         20.25   
Tchuente  Entreprenariat             D            35000         18.25   
Yemba                CDD             B             1750         10.99   

          Statut_du_pret  Taux_endettement Défaut  Nombre de credit historique  
Nom                                                                             
Akono                  1              0.59      Y                            3  
Akwa                   0              0.10      N                            2  
Arnaud                 1              0.57      N                            3  
Awa                    1              0.53      N                            2  
Dubois                 1              0.55      Y                            4  
Durand                 1              0.25      N                            2  
Ekounou                1              0.45      N                            3  
Mendong                1              0.44      N                            4  
Moussa                 1              0.42      N                            2  
Mvog-ada               1              0.16      N          

In [230]:
# Pour acceder à un element :
df.loc["Akono"]

Id_personne                            1
Age                                   40
Prenom                            Nathan
Revenu                             59000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          D
Montant du prêt                    35000
Taux_interet                       16.02
Statut_du_pret                         1
Taux_endettement                    0.59
Défaut                                 Y
Nombre de credit historique            3
Name: Akono, dtype: object

In [234]:
# selection de la ligne Mendong
df.loc["Mendong"]

Id_personne                            8
Age                                   24
Prenom                              Zibi
Revenu                             33000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          B
Montant du prêt                    35000
Taux_interet                       11.11
Statut_du_pret                         1
Taux_endettement                    0.44
Défaut                                 N
Nombre de credit historique            4
Name: Mendong, dtype: object

### 4. Statistiques descriptives

#### 4.1 Obtenir des statistiques de base (moyenne, médiane, écart_type)

In [240]:
# Description des varaibles quantitatives (NB: Il n'ya pas de variables qualitatives dans la sortie) 
df.describe()

Id_personne        Age         Revenu  Montant du prêt  Taux_interet  \
count     20.00000  20.000000      20.000000        20.000000     20.000000   
mean      10.50000  28.450000   82503.550000     25092.500000     12.253500   
std        5.91608   8.274724  105576.833252     15036.274341      3.899438   
min        1.00000  21.000000    9600.000000      1000.000000      7.140000   
25%        5.75000  23.000000   24750.000000      5250.000000      8.832500   
50%       10.50000  24.000000   64500.000000     35000.000000     11.125000   
75%       15.25000  32.500000   98290.000000     35000.000000     14.862500   
max       20.00000  50.000000  500000.000000     35000.000000     20.250000   

       Statut_du_pret  Taux_endettement  Nombre de credit historique  
count       20.000000         20.000000                    20.000000  
mean         0.800000          0.352500                     3.050000  
std          0.410391          0.154507                     0.887041  
min          0.000000          0.060000                     2.000000  
25%          1.000000          0.280000                     2.000000  
50%          1.000000          0.345000                     3.000000  
75%          1.000000          0.450000                     4.000000  
max          1.000000          0.590000                     4.000000

In [244]:
# desriptions des variables qualitatives
df.describe(include="object")

Prenom Type de domicile Travail Grade du pret Défaut
count      20               20      20            20     20
unique     18                3       3             6      2
top     Marie        Locataire     CDI             B      N
freq        2               10      11             6     18

In [246]:
# Compter les variables manquantes
df.isnull().sum() # me donne la somme des valeurs manquantes

Id_personne                    0
Age                            0
Prenom                         0
Revenu                         0
Type de domicile               0
Travail                        0
Grade du pret                  0
Montant du prêt                0
Taux_interet                   0
Statut_du_pret                 0
Taux_endettement               0
Défaut                         0
Nombre de credit historique    0
dtype: int64

In [248]:
df.isnull().mean()

Id_personne                    0.0
Age                            0.0
Prenom                         0.0
Revenu                         0.0
Type de domicile               0.0
Travail                        0.0
Grade du pret                  0.0
Montant du prêt                0.0
Taux_interet                   0.0
Statut_du_pret                 0.0
Taux_endettement               0.0
Défaut                         0.0
Nombre de credit historique    0.0
dtype: float64

#### 5.2 Suppression des colonnes

In [251]:
# suppression des colonnes
df.drop("Revenu",axis=1)

Id_personne  Age     Prenom Type de domicile         Travail  \
Nom                                                                      
Akono               1   40     Nathan        Locataire             CDI   
Akwa                2   35      Aicha     Propriétaire             CDI   
Arnaud              3   25      Matin        Locataire             CDD   
Awa                 4   23      Marie             Pret             CDI   
Dubois              5   24   Lachaise             Pret             CDI   
Durand              6   21     Bertin        Locataire             CDD   
Ekounou             7   44        Eli     Propriétaire             CDI   
Mendong             8   24       Zibi        Locataire             CDI   
Moussa              9   24     Hamado        Locataire             CDI   
Mvog-ada           10   50     Bertin     Propriétaire             CDI   
Mvogo              11   22    Melanie        Locataire             CDD   
Neba               12   21   Charlène        Locataire             CDD   
Ngo                13   34  Stephanie             Pret             CDI   
Ngono              14   26      Marie             Pret             CDI   
Omar               15   23    Mohamed             Pret  Entreprenariat   
Petit              16   32     Prince     Propriétaire  Entreprenariat   
Richard            17   23     Arnaud        Locataire             CDI   
Tchana             18   31     Albert        Locataire             CDD   
Tchuente           19   23       Isis        Locataire  Entreprenariat   
Yemba              20   24     Elodie             Pret             CDD   

         Grade du pret  Montant du prêt  Taux_interet  Statut_du_pret  \
Nom                                                                     
Akono                D            35000         16.02               1   
Akwa                 B             1000         11.14               0   
Arnaud               C             5500         12.87               1   
Awa                  C            35000         15.23               1   
Dubois               C            35000         14.27               1   
Durand               A             2500          7.14               1   
Ekounou              B            35000         12.42               1   
Mendong              B            35000         11.11               1   
Moussa               A            35000          8.90               1   
Mvog-ada             D             1600         14.74               1   
Mvogo                B            35000         10.37               1   
Neba                 A             4500          8.63               1   
Ngo                  A            35000          7.90               1   
Ngono                E            35000         18.39               1   
Omar                 A            35000          7.90               0   
Petit                B            30000         10.65               0   
Richard              A            35000          7.90               0   
Tchana               F            35000         20.25               1   
Tchuente             D            35000         18.25               1   
Yemba                B             1750         10.99               1   

          Taux_endettement Défaut  Nombre de credit historique  
Nom                                                             
Akono                 0.59      Y                            3  
Akwa                  0.10      N                            2  
Arnaud                0.57      N                            3  
Awa                   0.53      N                            2  
Dubois                0.55      Y                            4  
Durand                0.25      N                            2  
Ekounou               0.45      N                            3  
Mendong               0.44      N                            4  
Moussa                0.42      N                            2  
Mvog-ada              0.16      N                          

#### 5.3 Creer une nouvelle colonne calculée à partir d'autres

In [254]:
# Creation d'une nouvelle  comme etant la multiplication de deux colonnes du tableau
df['test']=df["Montant du prêt"]*df["Taux_interet"]
df

Id_personne  Age     Prenom  Revenu Type de domicile  \
Nom                                                              
Akono               1   40     Nathan   59000        Locataire   
Akwa                2   35      Aicha   70000     Propriétaire   
Arnaud              3   25      Matin    9600        Locataire   
Awa                 4   23      Marie   44000             Pret   
Dubois              5   24   Lachaise   54400             Pret   
Durand              6   21     Bertin    9900        Locataire   
Ekounou             7   44        Eli   77100     Propriétaire   
Mendong             8   24       Zibi   33000        Locataire   
Moussa              9   24     Hamado   24000        Locataire   
Mvog-ada           10   50     Bertin   80000     Propriétaire   
Mvogo              11   22    Melanie   25000        Locataire   
Neba               12   21   Charlène   10000        Locataire   
Ngo                13   34  Stephanie   95000             Pret   
Ngono              14   26      Marie  108160             Pret   
Omar               15   23    Mohamed  115000             Pret   
Petit              16   32     Prince  500000     Propriétaire   
Richard            17   23     Arnaud  120000        Locataire   
Tchana             18   31     Albert   92111        Locataire   
Tchuente           19   23       Isis  113000        Locataire   
Yemba              20   24     Elodie   10800             Pret   

                 Travail Grade du pret  Montant du prêt  Taux_interet  \
Nom                                                                     
Akono                CDI             D            35000         16.02   
Akwa                 CDI             B             1000         11.14   
Arnaud               CDD             C             5500         12.87   
Awa                  CDI             C            35000         15.23   
Dubois               CDI             C            35000         14.27   
Durand               CDD             A             2500          7.14   
Ekounou              CDI             B            35000         12.42   
Mendong              CDI             B            35000         11.11   
Moussa               CDI             A            35000          8.90   
Mvog-ada             CDI             D             1600         14.74   
Mvogo                CDD             B            35000         10.37   
Neba                 CDD             A             4500          8.63   
Ngo                  CDI             A            35000          7.90   
Ngono                CDI             E            35000         18.39   
Omar      Entreprenariat             A            35000          7.90   
Petit     Entreprenariat             B            30000         10.65   
Richard              CDI             A            35000          7.90   
Tchana               CDD             F            35000         20.25   
Tchuente  Entreprenariat             D            35000         18.25   
Yemba                CDD             B             1750         10.99   

          Statut_du_pret  Taux_endettement Défaut  \
Nom                                                 
Akono                  1              0.59      Y   
Akwa                   0              0.10      N   
Arnaud                 1              0.57      N   
Awa                    1              0.53      N   
Dubois                 1              0.55      Y   
Durand                 1              0.25      N   
Ekounou                1              0.45      N   
Mendong                1              0.44      N   
Moussa                 1              0.42      N   
Mvog-ada               1              0.16      N   
Mvogo                  1              0.41      N   
Neba                   1              0.45      N   
Ngo                    1              0.37      N   
Ngono                  1              0.32      N   
Omar                   0              0.30      N   
Petit                  0              0.06      N

In [256]:
# Mettre à jour une colonne
# Mettre à jour avec une valeur pour toutes les lignes
df["test"]=100
df

Id_personne  Age     Prenom  Revenu Type de domicile  \
Nom                                                              
Akono               1   40     Nathan   59000        Locataire   
Akwa                2   35      Aicha   70000     Propriétaire   
Arnaud              3   25      Matin    9600        Locataire   
Awa                 4   23      Marie   44000             Pret   
Dubois              5   24   Lachaise   54400             Pret   
Durand              6   21     Bertin    9900        Locataire   
Ekounou             7   44        Eli   77100     Propriétaire   
Mendong             8   24       Zibi   33000        Locataire   
Moussa              9   24     Hamado   24000        Locataire   
Mvog-ada           10   50     Bertin   80000     Propriétaire   
Mvogo              11   22    Melanie   25000        Locataire   
Neba               12   21   Charlène   10000        Locataire   
Ngo                13   34  Stephanie   95000             Pret   
Ngono              14   26      Marie  108160             Pret   
Omar               15   23    Mohamed  115000             Pret   
Petit              16   32     Prince  500000     Propriétaire   
Richard            17   23     Arnaud  120000        Locataire   
Tchana             18   31     Albert   92111        Locataire   
Tchuente           19   23       Isis  113000        Locataire   
Yemba              20   24     Elodie   10800             Pret   

                 Travail Grade du pret  Montant du prêt  Taux_interet  \
Nom                                                                     
Akono                CDI             D            35000         16.02   
Akwa                 CDI             B             1000         11.14   
Arnaud               CDD             C             5500         12.87   
Awa                  CDI             C            35000         15.23   
Dubois               CDI             C            35000         14.27   
Durand               CDD             A             2500          7.14   
Ekounou              CDI             B            35000         12.42   
Mendong              CDI             B            35000         11.11   
Moussa               CDI             A            35000          8.90   
Mvog-ada             CDI             D             1600         14.74   
Mvogo                CDD             B            35000         10.37   
Neba                 CDD             A             4500          8.63   
Ngo                  CDI             A            35000          7.90   
Ngono                CDI             E            35000         18.39   
Omar      Entreprenariat             A            35000          7.90   
Petit     Entreprenariat             B            30000         10.65   
Richard              CDI             A            35000          7.90   
Tchana               CDD             F            35000         20.25   
Tchuente  Entreprenariat             D            35000         18.25   
Yemba                CDD             B             1750         10.99   

          Statut_du_pret  Taux_endettement Défaut  \
Nom                                                 
Akono                  1              0.59      Y   
Akwa                   0              0.10      N   
Arnaud                 1              0.57      N   
Awa                    1              0.53      N   
Dubois                 1              0.55      Y   
Durand                 1              0.25      N   
Ekounou                1              0.45      N   
Mendong                1              0.44      N   
Moussa                 1              0.42      N   
Mvog-ada               1              0.16      N   
Mvogo                  1              0.41      N   
Neba                   1              0.45      N   
Ngo                    1              0.37      N   
Ngono                  1              0.32      N   
Omar                   0              0.30      N   
Petit                  0              0.06      N

In [260]:
# Mise à jour de la derniere colonne de la premiere ligne
df.iloc[0,-1]=1000
df

Id_personne  Age     Prenom  Revenu Type de domicile  \
Nom                                                              
Akono               1   40     Nathan   59000        Locataire   
Akwa                2   35      Aicha   70000     Propriétaire   
Arnaud              3   25      Matin    9600        Locataire   
Awa                 4   23      Marie   44000             Pret   
Dubois              5   24   Lachaise   54400             Pret   
Durand              6   21     Bertin    9900        Locataire   
Ekounou             7   44        Eli   77100     Propriétaire   
Mendong             8   24       Zibi   33000        Locataire   
Moussa              9   24     Hamado   24000        Locataire   
Mvog-ada           10   50     Bertin   80000     Propriétaire   
Mvogo              11   22    Melanie   25000        Locataire   
Neba               12   21   Charlène   10000        Locataire   
Ngo                13   34  Stephanie   95000             Pret   
Ngono              14   26      Marie  108160             Pret   
Omar               15   23    Mohamed  115000             Pret   
Petit              16   32     Prince  500000     Propriétaire   
Richard            17   23     Arnaud  120000        Locataire   
Tchana             18   31     Albert   92111        Locataire   
Tchuente           19   23       Isis  113000        Locataire   
Yemba              20   24     Elodie   10800             Pret   

                 Travail Grade du pret  Montant du prêt  Taux_interet  \
Nom                                                                     
Akono                CDI             D            35000         16.02   
Akwa                 CDI             B             1000         11.14   
Arnaud               CDD             C             5500         12.87   
Awa                  CDI             C            35000         15.23   
Dubois               CDI             C            35000         14.27   
Durand               CDD             A             2500          7.14   
Ekounou              CDI             B            35000         12.42   
Mendong              CDI             B            35000         11.11   
Moussa               CDI             A            35000          8.90   
Mvog-ada             CDI             D             1600         14.74   
Mvogo                CDD             B            35000         10.37   
Neba                 CDD             A             4500          8.63   
Ngo                  CDI             A            35000          7.90   
Ngono                CDI             E            35000         18.39   
Omar      Entreprenariat             A            35000          7.90   
Petit     Entreprenariat             B            30000         10.65   
Richard              CDI             A            35000          7.90   
Tchana               CDD             F            35000         20.25   
Tchuente  Entreprenariat             D            35000         18.25   
Yemba                CDD             B             1750         10.99   

          Statut_du_pret  Taux_endettement Défaut  \
Nom                                                 
Akono                  1              0.59      Y   
Akwa                   0              0.10      N   
Arnaud                 1              0.57      N   
Awa                    1              0.53      N   
Dubois                 1              0.55      Y   
Durand                 1              0.25      N   
Ekounou                1              0.45      N   
Mendong                1              0.44      N   
Moussa                 1              0.42      N   
Mvog-ada               1              0.16      N   
Mvogo                  1              0.41      N   
Neba                   1              0.45      N   
Ngo                    1              0.37      N   
Ngono                  1              0.32      N   
Omar                   0              0.30      N   
Petit                  0              0.06      N

In [264]:
# Modifier la valeur de la colonne d'une ligne en fonction d'une condition (remplacer D par F loan_grade)
df.loc[df["Travail"]=="CDI","Travail"]="CDD"
df

Id_personne  Age     Prenom  Revenu Type de domicile  \
Nom                                                              
Akono               1   40     Nathan   59000        Locataire   
Akwa                2   35      Aicha   70000     Propriétaire   
Arnaud              3   25      Matin    9600        Locataire   
Awa                 4   23      Marie   44000             Pret   
Dubois              5   24   Lachaise   54400             Pret   
Durand              6   21     Bertin    9900        Locataire   
Ekounou             7   44        Eli   77100     Propriétaire   
Mendong             8   24       Zibi   33000        Locataire   
Moussa              9   24     Hamado   24000        Locataire   
Mvog-ada           10   50     Bertin   80000     Propriétaire   
Mvogo              11   22    Melanie   25000        Locataire   
Neba               12   21   Charlène   10000        Locataire   
Ngo                13   34  Stephanie   95000             Pret   
Ngono              14   26      Marie  108160             Pret   
Omar               15   23    Mohamed  115000             Pret   
Petit              16   32     Prince  500000     Propriétaire   
Richard            17   23     Arnaud  120000        Locataire   
Tchana             18   31     Albert   92111        Locataire   
Tchuente           19   23       Isis  113000        Locataire   
Yemba              20   24     Elodie   10800             Pret   

                 Travail Grade du pret  Montant du prêt  Taux_interet  \
Nom                                                                     
Akono                CDD             D            35000         16.02   
Akwa                 CDD             B             1000         11.14   
Arnaud               CDD             C             5500         12.87   
Awa                  CDD             C            35000         15.23   
Dubois               CDD             C            35000         14.27   
Durand               CDD             A             2500          7.14   
Ekounou              CDD             B            35000         12.42   
Mendong              CDD             B            35000         11.11   
Moussa               CDD             A            35000          8.90   
Mvog-ada             CDD             D             1600         14.74   
Mvogo                CDD             B            35000         10.37   
Neba                 CDD             A             4500          8.63   
Ngo                  CDD             A            35000          7.90   
Ngono                CDD             E            35000         18.39   
Omar      Entreprenariat             A            35000          7.90   
Petit     Entreprenariat             B            30000         10.65   
Richard              CDD             A            35000          7.90   
Tchana               CDD             F            35000         20.25   
Tchuente  Entreprenariat             D            35000         18.25   
Yemba                CDD             B             1750         10.99   

          Statut_du_pret  Taux_endettement Défaut  \
Nom                                                 
Akono                  1              0.59      Y   
Akwa                   0              0.10      N   
Arnaud                 1              0.57      N   
Awa                    1              0.53      N   
Dubois                 1              0.55      Y   
Durand                 1              0.25      N   
Ekounou                1              0.45      N   
Mendong                1              0.44      N   
Moussa                 1              0.42      N   
Mvog-ada               1              0.16      N   
Mvogo                  1              0.41      N   
Neba                   1              0.45      N   
Ngo                    1              0.37      N   
Ngono                  1              0.32      N   
Omar                   0              0.30      N   
Petit                  0              0.06      N

#### 6. Fusion et jointure de Data Frames

In [273]:
# Creation des dataFrames exemple
data1= {
    "ID":[1, 2, 3, 4], "Prenom":["Alice", "Bob", "Charlie", "David"]
}
data2= {
    "ID":[3, 4, 5, 6], "Prenom":["Paris", "Lyon", "Marseille", "Toulouse"]
}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)


In [277]:
df1

ID   Prenom
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

In [279]:
df2

ID     Prenom
0   3      Paris
1   4       Lyon
2   5  Marseille
3   6   Toulouse

In [287]:
# effectuer une jointure interne (inner join)
inner_join = df1.merge(df2, on="ID", how="inner")

In [289]:
# effectuer une jointure externe (outer join)
outer_join = df1.merge(df2, on="ID", how="outer")

In [291]:
# Effectuer une jointure gauche (left join)
left_join = df1.merge(df2, on="ID", how="left")

In [293]:
# Effectuer une jointure droite (right join)
right_join = df1.merge(df2, on="ID", how="right")

In [295]:
# Affichage des resultats
print("Inner_join:")
print(inner_join)

Inner_join:
   ID Prenom_x Prenom_y
0   3  Charlie    Paris
1   4    David     Lyon


In [299]:
print("\nouter join:")
print(outer_join)


outer join:
   ID Prenom_x   Prenom_y
0   1    Alice        NaN
1   2      Bob        NaN
2   3  Charlie      Paris
3   4    David       Lyon
4   5      NaN  Marseille
5   6      NaN   Toulouse


In [301]:
print("\nLeft join:")
print(left_join)
print("\nRight join:")
print(right_join)


Left join:
   ID Prenom_x Prenom_y
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie    Paris
3   4    David     Lyon

Right join:
   ID Prenom_x   Prenom_y
0   3  Charlie      Paris
1   4    David       Lyon
2   5      NaN  Marseille
3   6      NaN   Toulouse


### 7. Enregistrer la base 
#### 7.1 Enregistrer en csv

In [ ]:
# Enregistrer en csv
df.to_csv("test.csv")

In [ ]:
# enregistrer en json
df.to_json("test.json")