### 1. Installation et chargement de Numpy 

In [3]:
!pip install numpy
import numpy as np

### 2. Creation des données (ou tableau) avec numpy

#### 2.1 Créer un numpy array avec une liste/lise de liste (matrice)

In [13]:
# Creation à partir d'une liste
liste=[1,2, 3, 4, 5] # definition de la liste
array_with_liste = np.array(liste)
print(array_with_liste)

[1 2 3 4 5]


### Creation à partir d'une matrice

In [17]:
# Creation d'un numpy array à partir d'une liste de listes (matrices)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2.2 Creer un numpy array à partir des onctions intégrées

In [21]:
# Creer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Creer un numpy array a a partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
# Creer un numpy arry avec la fonction eye
array_eye = np.eye(6) # pour creer la matrice identité de dimension 6
array_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
# Creer un numpay array avec la fonction arange: pour creer des nombres entre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2) # 2 etant le pas 
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [37]:
# Creer un numpy array avec la fonction linspace # generer une sequence de nombre entre deux valeurs données
# avec un nombre de points  données
array_linspace = np.linspace(0, 1, 5) # tres utile pour les graphiques
array_linspace # Creer des points equidistants entre 0 et 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
# Creer un numpy array de valeurs aléatoires avec la fonction random
array_random =np.random.random((4,3)) # utile pour initialiser les poids dans les reseaux de neurones, génerer des données
print(array_random) # me geere un tableau de données de 4 lignes et 3 colonnes
# si c'est un vecteur de talle taille  3, On aura (3) , une matrice de taille 2x2, on aura (2,2)

[[0.84191836 0.55851081 0.23637749]
 [0.83299482 0.8582512  0.28096214]
 [0.97244011 0.08524444 0.70554034]
 [0.60477313 0.70218439 0.91513696]]


### 3 Fonctions mathématiques et statistiques avec numpy

In [ ]:
# Fonctions mathématiques basiques
arrayl= array_wise_liste
array_sum = np.sum(arrayl)
array_mean = np.mean(arrayl)
array_std = np.std(arrayl)
array_min = np.min(arrayl)
array_max = np.max(arrayl)
array_sqrt = np.sqrt(arrayl)
array_abs =np.abs(arrayl)
array_power = np.power(arrayl)
array_exp = np.exp(arrayl)
array_log = np.log(arrayl)
array_sin = np.sin(arrayl)
array_median = np.median(arrayl)
array_sum

### 4 Manipulation des matrices avec Numpy

In [49]:
# Produit matriciel
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [51]:
# Transposée
transpose = np.transpose(array_with_matrice)
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [55]:
# Inversion (pour les matrices carrées non singulieres)
inverse = np.linalg.inv(array_eye)
print(inverse)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-0. -0. -0.  1. -0. -0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [59]:
# Detreminant
determinant = np.linalg.det(array_eye)
print(determinant)

1.0


### 4 Acceder aux elements, selectionner, modifier et mettre à jour un numpy array

In [64]:
# Acces aux elements
arrayl = np.array([1,2,3,4,5])
premier_element = arrayl[0]
print(premier_element)
# pour accerder au dernier element, ce sera arrayl[-1]

1


In [68]:
# Modification d'un element
arrayl[0] = 10
print(arrayl)

[10  2  3  4  5]


In [78]:
# Selection des elements qui respectent une condition
condition = arrayl > 5
elements_respectant_condition = arrayl[condition]
elements_respectant_condition

array([10])

In [84]:
condition = arrayl > 3
condition
indices = np.where(arrayl > 3) # revoie les indices des elements superieurs à 3
indices

(array([0, 3, 4], dtype=int64),)

In [86]:
arrayl > 3

array([ True, False, False,  True,  True])

In [92]:
# Utilisation de np.where qui permet de faire des filtres
indices = np.where(arrayl > 5)
elements_respectant_condition_np_where = arrayl[indices]
print(elements_respectant_condition_np_where)

[10]


In [96]:
# Mise à jour d'un numpy array
arrayl[condition]=0 # avec condition = arrayl > 3 , permet donc de remplacer par des 0 tous les elements > 3
print(arrayl)

[0 2 3 0 0]


In [102]:
# Slicing et indexaction avncée
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing
premiere_ligne = array6[0, :] # pour recuperer la premiere ligne (indice 0)
premiere_ligne

array([1, 2, 3])

In [104]:
# prepiere colonne
premiere_colonne = array6[:,0]
premiere_colonne

array([1, 4, 7])

In [108]:
# Sous matrice
sous_matrice = array6[1:3,1:3] # [1:3] pour les lignes prend 1 à 2 uniquement, et pour les colonnes prend 2 à 3 uniquement
sous_matrice

array([[5, 6],
       [8, 9]])

In [110]:
# Indexation avancée
lignes = [0, 1] #  toutjours decaler de 1 pour identifier les valeurs
colonnes =[1, 2] # declaler egalement de 1
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [112]:
# Operations elementaires et diffusion (broacasting)
array7 =np.array([1,2,3])
array8 = np.array([4, 5, 6])

# Addition elementaire
array_addition = array7 + array8
array_addition

array([5, 7, 9])

In [116]:
# Multiplication elementaire
array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [118]:
# Diffusion (broadcasting)
array9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array10 = np.array([1, 2, 3])
array9 + array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

### 6 Redimensionnement, append, type de données taille etc

In [121]:
# r redimensionné le numpy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3, 3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [125]:
# Ajouter des elemnts dans un numpy array
arrayl_allonge = np.append(arrayl, [6, 7, 8])
print(arrayl_allonge)

[0 2 3 0 0 6 7 8]


In [128]:
# Connaitre les caracteristiques d'un numpy array
array_with_matrice.shape # dimension de l'array

(3, 3)

In [132]:
# connaitre le type d'objet
type(array_with_matrice) # type de l'objet

numpy.ndarray

In [134]:
# Connaitre le type des él
arrayl.dtype # type des objets

dtype('int32')

In [136]:
array7 = np.array(['1', '2', '3'])
array7.dtype

dtype('<U1')