### 1. Installation et chargement de Numpy 

In [3]:
!pip install numpy
import numpy as np

### 2. Creation des données (ou tableau) avec numpy

#### 2.1 Créer un numpy array avec une liste/lise de liste (matrice)

In [13]:
# Creation à partir d'une liste
liste=[1,2, 3, 4, 5] # definition de la liste
array_with_liste = np.array(liste)
print(array_with_liste)

[1 2 3 4 5]


### Creation à partir d'une matrice

In [17]:
# Creation d'un numpy array à partir d'une liste de listes (matrices)
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2.2 Creer un numpy array à partir des onctions intégrées

In [21]:
# Creer un numpy array à partir de la fonction zeros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Creer un numpy array a a partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
# Creer un numpy arry avec la fonction eye
array_eye = np.eye(6) # pour creer la matrice identité de dimension 6
array_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
# Creer un numpay array avec la fonction arange: pour creer des nombres entre entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 11, 2) # 2 etant le pas 
array_arange

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# Creer un numpy array avec la fonction linspace # generer une sequence de nombre entre deux valeurs données
# avec un nombre de points  données
array_linspace ) np.linspace(0, 1, 5) # tres utile pour les graphiques
array_linspace