In [4]:
print("Bonjour mad")


Bonjour mad


In [7]:
# création d'un booleen
temp=True

In [8]:
type(temp)

bool

In [9]:
temp1=False
type(temp1)

bool

In [10]:
str(temp1)

'False'

In [18]:
# operation entre les variables
x=2
y=3
z=x+y
print(z)

5


In [12]:
# multiplication
z=x*y
print(z)

255


In [20]:
# recuperer la partie entiere d'une division
z=x//y
print(z)

0


In [22]:
# recuperer le reste de la division euclidienne
z=x%y
print(z)

2


In [21]:
# ici on a 2 expo 3
z=x**y
z

8

#### opérations avancées: Division entiere //, modulo %, et exponentiation **

# Condition logique simple en python

### Opérateurs logiques: and, or, not
### pour les comparaisons: ==, !=, >,<, >=,<=

In [23]:
x=True
y=False
z=x and y # on peut utiliser & a la place du and
z

False

In [25]:
z=x or y
z

True

In [26]:
z= not x
z

False

In [27]:
age=24
age

24

In [29]:
## tester si l'age est egale à 24 ans
age==24

True

In [30]:
age<24

False

In [31]:
age>24

False

In [32]:
## tester la difference
age !=24

False

In [33]:
# On peut egalement tester si l'age est <= ou >= 

# Création des fonctions en python

### Fonction lambda: création de fonctions simples ave c une seule ligne

In [38]:
addition=lambda x,y, z:x+y+z # On peut rajouter autant de parametres

In [39]:
temp=addition(x=5, y=10,z=20)
temp

35

# Création fonction classique

In [41]:
def addition(a,b,c):
    resultat=a+b+c
    
    return resultat

In [42]:
addition(a=2,b=3,c=4)

9

In [ ]:
def addition(a,b,c):
    resultat=a+b
    resultat=resultat+c
    
    return resultat

### Multiplication

In [43]:
def multiplication(a,b,c):
    resultat=a*b
    resultat=resultat*c
    
    return resultat

In [44]:
multiplication(a=2,b=3,c=4)

24

### NB: une variable definie dans une fonction n'est accessible que dans cette fonction

In [45]:
def multiplication(a,b,c):
    """"
    expliquer la fonction
    param
    return
    """"
    d=5
    resultat=a*b #commmenter les fonctions
    resultat=resultat*c*d
    
    return resultat
## avec des valeurs par defauts, il est possible de taper juste multiplication()

###  exemple d'application

In [46]:
mutliplication=lambda x,y:x*y

In [47]:
mutliplication(5,4)

20

In [48]:
### creation d'une fonction par def
def celsius_to_fahrenheit(celsius):
    fahrenheit=(celsius*9/5)+32
    return fahrenheit
celsius_to_fahrenheit(2)


35.6

# Partie2: Structures de controle
   ### if: comment prendre des decisions dans vos programmes
     

In [52]:
# decisions simples 
temperature = 6
if temperature > 30:
    print("il fait chaud")

In [53]:
## pour temp = 6 il n'y aura pas de reponse car temp = 6, en changeant cette valeur temp=35
temperature = 35
if temperature > 30:
    print("il fait chaud")

il fait chaud


In [54]:
## Autres possibilités
temperatue = 35
if True:
    print("il fait chaud")

il fait chaud


In [55]:
# decison avec alternative(Else)
temperature = 35
if temperature > 30:
    print("il fait chaud")
else:
    print("il fait froid")
    

il fait chaud


In [58]:
# Decision avec multiples alternatives (Elif)
note = "A" ## on peut toujours changer la note A, B, C,...,Z
if note =="A":
    print("Excellent")
elif note == "B":
    print("Bien")
elif note == "C":
    print("Moyen")
else:
    print("A améliorer")

A améliorer


In [59]:
# Conditions multiples conditions
note = 17 ## possibilité de modifié la note
age = 18 # et ici l'age

if (note >= 16) and (age <= 20): # on peut utiliser and, or
    print("Bourse acceptée")
else :
    print("Pas de Bourse")

Bourse acceptée


In [61]:
# Conditions imbriquées
if age <=20 :
    if note >16:
        print("bourse acceptée")
    else:
        print("Pas de bourse")
else:
    print("Dossier à retraiter")

bourse acceptée


In [62]:
# Exemple: Creation d'une fonction

def classer_age(x):
    if x<=12:
        resultat = "Enfant"
    elif (x>12) & (x<=17):
        resultat= "Adolescent"
    elif (x>=18) & (x<=59):
        resultat = "Adulte"
    elif (x>=60):
        resultat = "Senior"
    else: 
        resultat = "Age invalide"
    return resultat
classer_age(12)

'Enfant'

### Présentation de la boucle for for simple

In [64]:
for i in range(0,10,1): # 0=min, 10=max, et 1=le pas
    print(i)
range?? ## pour detailler la fonction (pour voir les fonctions natives en python)

0
1
2
3
4
5
6
7
8
9


In [65]:
for i in range(10,0,-1): 
    print(i)

10
9
8
7
6
5
4
3
2
1


In [66]:
range(10,0,-1)

range(10, 0, -1)

In [67]:
# for avec une condition if

for i in range(10,0,-1):
    if i % 2 == 0:
        print(i, "est un nombre pair")
    else :
        print(i, "est un nombre impair")

10 est un nombre pair
9 est un nombre impair
8 est un nombre pair
7 est un nombre impair
6 est un nombre pair
5 est un nombre impair
4 est un nombre pair
3 est un nombre impair
2 est un nombre pair
1 est un nombre impair


### While (tant que) : executer des instructions de maniere répétée

In [68]:
# while de base
compteur = 1

while compteur < 10:
    compteur += 1 # compteur = compteur + 1
    print(compteur)

2
3
4
5
6
7
8
9
10


In [69]:
compteur = 1

while compteur < 10:
    print(compteur)
    compteur += 1 # compteur = compteur + 1

1
2
3
4
5
6
7
8
9


In [72]:
# Boucle infinie ave While et l'instruction brak
compteur=1
while True:
    print(compteur)
    compteur +=1 # compteur = compteur + 1
    if compteur == 5:
       break

1
2
3
4


# Types de données en Python

## Listes

In [73]:
# Liste de nombre
liste_age =[15, 17, 23, 29, 45, 50, 45, 67]
print(liste_age)
type(liste_age)

[15, 17, 23, 29, 45, 50, 45, 67]


list

In [74]:
# Taille des élements d'une liste
len(liste_age)

8

In [77]:
# liste de chaine de caracteres
liste_nom = ["MAD", "STAT", "ANGLAIS","PROB"]
print(liste_nom)

['MAD', 'STAT', 'ANGLAIS', 'PROB']


In [76]:
# taille de cet objet
len(liste_nom)

4

In [80]:
# Liste de listes
liste =[ liste_age,liste_nom]
print(liste)
type(liste)

[[15, 17, 23, 29, 45, 50, 45, 67], ['MAD', 'STAT', 'ANGLAIS', 'PROB']]


list

In [81]:
# Taille
len(liste)

2

## Read

In [82]:
# lire un element au debut
# liste de nombre
liste_age=[15, 17, 23, 29, 45, 50, 45, 67]
liste_age[0]

15

In [83]:
# lire le dernier element
liste_age[-1]

67

In [84]:
# récupération d'un élément sur la liste
liste_age[len(liste_age)-1]

67

In [85]:
# lire une position quelconque
liste_age[2] # element de la liste de la quatrieme position

23

In [ ]:
# premier élement de la premiere liste
liste[0][0]

In [86]:
# liste sur plusieurs positions qui se suivent
liste_age[0:3] # on peut choisir n'imporet quel élement

[15, 17, 23]

In [87]:
liste_age[1:4]

[17, 23, 29]

In [90]:
# faire une boucle sur une liste
for nom in liste_nom :
    print(nom)

MAD
STAT
ANGLAIS
PROB


## Update

In [93]:
# Modification direct à partir d'un index
liste_nom[1] = "fin"
print(liste_nom)

['MAD', 'fin', 'ANGLAIS', 'PROB']


In [94]:
# Ajouter un element à la fin de la liste
liste_nom.append("GLM")
liste_nom

['MAD', 'fin', 'ANGLAIS', 'PROB', 'GLM']

In [95]:
# ajouter un element àune position précise (insert)
liste_nom.insert(1,"chimie")
liste_nom

['MAD', 'chimie', 'fin', 'ANGLAIS', 'PROB', 'GLM']

## Delete

In [97]:
# Supprimer l'élément à un index spécifique (del liste[index])
del liste_nom[3] # supprime ici "l'anglais"
liste_nom

['MAD', 'chimie', 'fin', 'GLM']

In [98]:
# Supprimer la premiere occurence de l'element (remove)
liste_age = [15, 17, 23, 29, 45, 50, 45, 67] # supprime le premier element de la liste
liste_age.remove(15)

In [99]:
liste_age

[17, 23, 29, 45, 50, 45, 67]

In [100]:
# supprimer et retourner l'element à l'index  donné pop
liste_age.pop(0)

17

In [101]:
liste_age

[23, 29, 45, 50, 45, 67]

## String

In [102]:
nom= "Brech"

In [105]:
nom[:3] # permet de deonner les trois premires lettres dela chaine de caractere et pour le dernier nom[-1]

'Bre'

###  Tuples

In [106]:
# un tuple est une collection d'éléments ordonnée et immuable en python
# Avantage: moins d'espace mémoire que les listes

In [107]:
# Create
mon_tuple =(3, 6, 7, 8)
mon_tuple

(3, 6, 7, 8)

In [108]:
# Read
mon_tuple[0] # premier élément
mon_tuple[-1] # dernier element

mon_tuple[1]


6

In [109]:
# update
# on ne peut pas modifier les tuples comme sur les listes, on peut par contre rajouter des élements
mon_tuple + (3,5)

(3, 6, 7, 8, 3, 5)

In [110]:
# delete
del mon_tuple

# Sets

- 1) Un set est une collection d'elements non ordonnée, modifiable et unique en Python. Chaque element dans un set est distinct et ne peut apparaitre qu'une seule fois.
- 2) Avantage: les Sets sont optimisées pour vérifier rapidement si un element est present dans la collection, ce qui le rend ideaux pour les operations comme les unionsn intersection, et les differences d'ensembles.

In [111]:
# Create
mon_set={4, 5, 7, 7, 7, 6, 6}
mon_set

{4, 5, 6, 7}

In [113]:
# Read (for)
for element in mon_set:
    print(element)

4
5
6
7


In [114]:
# Read if pour verifier la présence
if 4 in mon_set:
    print("3 est disponible")
else:
    print("3 est non disponible")

3 est disponible


# Partie 3:

### Corriger exercice sur les listes

In [125]:
# Premiere Solution

liste_nombre = [12, 35, 12, 9, 56, 24, 35, 12, 89, 24, 35, 12]
nombre_cherche = 12
nombre_remplace = 100

print("Liste avant remplacement", liste_nombre)

for i in range(len(liste_nombre)):
    if liste_nombre[i] == nombre_cherche:
        liste_nombre[i] = nombre_remplace 

print("liste apres remplacement", liste_nombre)

Liste avant remplacement [12, 35, 12, 9, 56, 24, 35, 12, 89, 24, 35, 12]
liste apres remplacement [100, 35, 100, 9, 56, 24, 35, 100, 89, 24, 35, 100]


In [127]:
# deuxieme solution

liste_nombre = [12, 35, 12, 9, 56, 24, 35, 12, 89, 24, 35, 12]
nombre_cherche = 12
nombre_remplace = 100

liste_apres=liste_nombre

print("liste avant remplacement", liste_nombre)

compteur = 0
for i in liste_apres:
    if i==nombre_cherche :
        liste_apres[compteur] = nombre_remplace
    compteur += 1 # equivalent à compteur = compteur + 1

print("liste apres remplacement", liste_apres)

liste avant remplacement [12, 35, 12, 9, 56, 24, 35, 12, 89, 24, 35, 12]
liste apres remplacement [100, 35, 100, 9, 56, 24, 35, 100, 89, 24, 35, 100]


In [128]:
# troisieme possibilité
def remplacer (liste_nombre, nombre_cherche, nombre_remplace):
    for i in range(len(liste_nombre)):
        if liste_nombre[i] == nombre_cherche:
            liste_nombre[i] = nombre_remplace
    return liste_nombre
print("liste apres remplacement", liste_nombre)

liste apres remplacement [100, 35, 100, 9, 56, 24, 35, 100, 89, 24, 35, 100]


# Les dictionnaires

- a) Un dictionnaire en Python est une collection d'elements non ordonnées, modifiables et indexés. chaque élement dans un dictionnaire est une paire clé-valeur, ou chaque clé est unique.
- b) Avantage: les dictionnaires sont optimisés pour recuper rapidement  des valeurs lorsque vous connaissez la clé, ce qui les rend idéaux pour stocker des données qu'il est necessaire de recuperer efficacement.

## Create

In [129]:
# Création d'un dictionnaire

In [166]:
depense_mensuelle = {"loyer": 500, 
                    "divertissement": 200,
                    "sante": 100,
                    "transport": 20}
depense_mensuelle

{'loyer': 500, 'divertissement': 200, 'sante': 100, 'transport': 20}

In [132]:
# type

type(depense_mensuelle)

dict

In [167]:
# impossible d'avoir deux clés identiques

depense_mensuelle = {"loyer": 500, 
                    "divertissement": 200,
                    "sante": 100,
                    "transport": 20,
                    "sante":20}
depense_mensuelle

## recupere juste la deuxieme valeur de sante, On s'assure juste que la clé soit unique

{'loyer': 500, 'divertissement': 200, 'sante': 20, 'transport': 20}

In [138]:
len(depense_mensuelle)

4

In [ ]:
# utilisation en machine learning

param = {"nb_iteration": 500, 
                    "nbr_variable": 200,
                    "sante": 100,
                    "transport": 20,
                    "sante":20}

In [168]:
# Possibilibité de creer des dictionnaires de dictionnaires
depense_janvier = {"loyer": 500, 
                    "divertissement": 200,
                    "sante": 100,
                    "transport": 20,
                    "sante":20}

depense_fevrier = {"loyer": 400, 
                    "divertissement": 300,
                    "sante": 400,
                    "transport": 20,
                    "sante":30}
depense_annuelle={"janvier": depense_janvier,
                 "fevrier": depense_fevrier}

print(depense_annuelle)

{'janvier': {'loyer': 500, 'divertissement': 200, 'sante': 20, 'transport': 20}, 'fevrier': {'loyer': 400, 'divertissement': 300, 'sante': 30, 'transport': 20}}


In [137]:
len(depense_annuelle)

2

## Read

In [140]:
# lire une clé
loyer=depense_mensuelle["loyer"]
print(loyer)

500


In [143]:
# tester une autre clé
# depense_mensuelle.get??

temp=depense_mensuelle.get("loisir")
print(temp)

None


In [146]:
# Obtenir toutes les clés  disponibles
depense_mensuelle.keys()
depense_mensuelle['divertissement']

200

In [169]:
depense_mensuelle.keys()

dict_keys(['loyer', 'divertissement', 'sante', 'transport'])

In [148]:
# Acceder à une clé specifique
depense_mensuelle[list(depense_mensuelle.keys())[1]] # on transforme d'abord en liste depense_mensuelle qui est un dict

200

In [170]:
# Obtenir les valeurs
depense_mensuelle.values()

dict_values([500, 200, 20, 20])

In [171]:
# obtenir les items
depense_mensuelle.items()

dict_items([('loyer', 500), ('divertissement', 200), ('sante', 20), ('transport', 20)])

In [151]:
# taille su dictionnaire
len(depense_mensuelle)

4

## Update

In [172]:
# mettre à jour la valeur d'une clé dans le dictionnaire

depense_mensuelle['loyer'] = 600
print(depense_mensuelle)

{'loyer': 600, 'divertissement': 200, 'sante': 20, 'transport': 20}


In [173]:
# Ajouter un nouvel élement dans le dictionnaire
depense_mensuelle["vetement"]=200
print(depense_mensuelle)

{'loyer': 600, 'divertissement': 200, 'sante': 20, 'transport': 20, 'vetement': 200}


## Delete

In [174]:
# supprimer une clé (del)
del depense_mensuelle["vetement"]
print(depense_mensuelle)

{'loyer': 600, 'divertissement': 200, 'sante': 20, 'transport': 20}


In [175]:
# methode pop
transport = depense_mensuelle.pop('transport')


In [176]:
print(transport)
print(depense_mensuelle)

20
{'loyer': 600, 'divertissement': 200, 'sante': 20}


## Utilisation des dictionnaires dans les boucles for

In [177]:
# for avec les clés
for keys in depense_mensuelle.keys(): #  le nom que l'on met dans le for n'a pas trop d'importance, on peut remplacer keys=k=v
    print(keys) 

loyer
divertissement
sante


In [179]:
# for avec les values
for val in depense_mensuelle.values():
    print(val)

600
200
20


In [182]:
# for avec les clés et les valeurs

for k,v in depense_annuelle.items():
    print("Ceci est la clé", k)

Ceci est la clé janvier
Ceci est la clé fevrier


In [183]:
for i,j in v.items(): ## le dictionnaire affiché est celui de fevrier 
        print(i,j)

loyer 400
divertissement 300
sante 30
transport 20


In [181]:
# for avec les clés et les valeurs

for k,v in depense_annuelle.items():
    print("Ceci est la clé", k)
    for i,j in v.items():
        print(i,j)

Ceci est la clé janvier
loyer 500
divertissement 200
sante 20
transport 20
Ceci est la clé fevrier
loyer 400
divertissement 300
sante 30
transport 20


In [180]:
# for avec les clés et les valeurs
for k,v in depense_mensuelle.items():
    print("ceci est la clé ",k, "ceci est la valeur",v)

ceci est la clé  loyer ceci est la valeur 600
ceci est la clé  divertissement ceci est la valeur 200
ceci est la clé  sante ceci est la valeur 20


### listes en comprehension

In [187]:
# creer la liste des carrés de 0 à 99

In [188]:
# Approche classique

liste_carre = []
for i in range(100):
    liste_carre.append(i**2) # ajouter un element à la  derniere position d'une liste
print(liste_carre)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [189]:
# definition en comprehension
liste_carre_com = [x ** 2 for x in range(99)]
print(liste_carre_com)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604]


In [191]:
# Filtrer une liste pour ne garder que les nombres  pairs
liste_carre_com_pair = [x ** 2 for x in range(99) if x % 2 == 0] # la condition if pour montrer que le reste de la division=0
print(liste_carre_com_pair)
type(liste_carre_com_pair)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604]


list

In [192]:
# Transformer des noms en majuscule
liste_nom = ["jean", "paul", "marie"]
liste_nom_majuscule = [x.upper() for x in liste_nom]
liste_nom_majuscule

['JEAN', 'PAUL', 'MARIE']

### Exercice en liste de comprehension 

In [194]:
mots=["Bonjour", "le", "monde", "Python", "est", "génial"]

mots_long=[x for x in mots if len(x)>=3] # le x entre for et in peut etre remplacé par n'importe quel lettre
mots_long

['Bonjour', 'monde', 'Python', 'est', 'génial']

### Dictionnaire en comprehension

In [195]:
# dictionnaire avec les nombres au carré de 0 à 99
dict_carre = {k:k**2 for k in range(0,99)}
print(dict_carre)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521, 40: 1600, 41: 1681, 42: 1764, 43: 1849, 44: 1936, 45: 2025, 46: 2116, 47: 2209, 48: 2304, 49: 2401, 50: 2500, 51: 2601, 52: 2704, 53: 2809, 54: 2916, 55: 3025, 56: 3136, 57: 3249, 58: 3364, 59: 3481, 60: 3600, 61: 3721, 62: 3844, 63: 3969, 64: 4096, 65: 4225, 66: 4356, 67: 4489, 68: 4624, 69: 4761, 70: 4900, 71: 5041, 72: 5184, 73: 5329, 74: 5476, 75: 5625, 76: 5776, 77: 5929, 78: 6084, 79: 6241, 80: 6400, 81: 6561, 82: 6724, 83: 6889, 84: 7056, 85: 7225, 86: 7396, 87: 7569, 88: 7744, 89: 7921, 90: 8100, 91: 8281, 92: 8464, 93: 8649, 94: 8836, 95: 9025, 96: 9216, 97: 9409, 98: 9604}


In [196]:
# dictionnaire uniquement avec les nombres pairs

dict_carre_pair = {k:k**2 for k in range(0,99) if k % 2 ==0}
print(dict_carre_pair)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400, 22: 484, 24: 576, 26: 676, 28: 784, 30: 900, 32: 1024, 34: 1156, 36: 1296, 38: 1444, 40: 1600, 42: 1764, 44: 1936, 46: 2116, 48: 2304, 50: 2500, 52: 2704, 54: 2916, 56: 3136, 58: 3364, 60: 3600, 62: 3844, 64: 4096, 66: 4356, 68: 4624, 70: 4900, 72: 5184, 74: 5476, 76: 5776, 78: 6084, 80: 6400, 82: 6724, 84: 7056, 86: 7396, 88: 7744, 90: 8100, 92: 8464, 94: 8836, 96: 9216, 98: 9604}


# Exercice
Considerer le dictionnaire suivant inventaire = {'pomme':30, 'bananes':15, 'cerises': 20}

creer un dictionnaire en comprehension qui va inverser les clés et les valeurs du dictionnaire inventaire

In [197]:
inventaire = {'pomme':30, 'bananes':15, 'cerises': 20}
dict_inverse = {v:k for k,v in inventaire.items()}
dict_inverse

{30: 'pomme', 15: 'bananes', 20: 'cerises'}

# fonctions natives en Python

### la documentation des fonctions  natives est disponible ici: https://docs.python.org/fr/3/library/functions.html

In [ ]:
# print
print("Bonsoir")

In [202]:
# format (à connaitre) # peut etre utiliser pour automatiser
temperature = 2
ville = "Brest"
resultat = "La temperature à {} est de {}".format(ville,temperature)
print(resultat)

La temperature à Brest est de 2


In [203]:
# autre possibilité
resultatbis = f"La temperature à {ville} est de {temperature}"
print(resultatbis)

La temperature à Brest est de 2


In [204]:
# input
age = input("quel est votre age?")

quel est votre age?16


In [206]:
print(age)
type (age)

16


str

In [207]:
# transormer les string en interger
age_int = int(age)
type(age_int)

int

In [208]:
# abs
x = -5
abs(x)

5

In [209]:
# round
y = 1.4555
round(y)


1

In [210]:
# max (liste)
liste_entier=[5, 4, 3, 6, 377]
max(liste_entier)

377

In [211]:
# min (liste)
liste_entier=[5, 4, 3, 6, 377]
min(liste_entier)

3

In [212]:
# sum
sum(liste_entier)

395

In [213]:
# all (vrai ou different de zero)
all(liste_entier) # tous les élements de la liste sont vrais , c'est a dire different de 0

True

In [214]:
# any (vrai ou different de 0 )
any(liste_entier)

True

In [215]:
# range
plage = range(0,199,3)

In [216]:
# type
type(liste_entier)

list

In [219]:
# conversion list, tuple, dictionnaire
list(plage)
trans_tuple = tuple(plage) # conversion de la liste en tuple


[0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99,
 102,
 105,
 108,
 111,
 114,
 117,
 120,
 123,
 126,
 129,
 132,
 135,
 138,
 141,
 144,
 147,
 150,
 153,
 156,
 159,
 162,
 165,
 168,
 171,
 174,
 177,
 180,
 183,
 186,
 189,
 192,
 195,
 198]

In [ ]:
# conversion float, int, string

In [221]:
test = float(0)
test

0.0

# creation de packages

In [224]:
#  creation d'u  module
# creation faite sur spyder du module

In [226]:
# Importer et renommer tout le module
import mon_module as mod

In [227]:
# creation de la liste
chiffre_affaires= [3000, 5000, 4000, 8000, 10000]

In [229]:
# application de la fonction
statdescr=mod.statdescriptive(chiffre_affaires)
statdescr

{'min': 3000, 'max': 10000, 'somme': 30000, 'moyenne': 6000.0}

In [230]:
# somme du chiffre d'affaire
sommeca=mod.somme_element(chiffre_affaires)
sommeca

30000

In [232]:
# importer une partie
from mon_module import statdescriptive

In [233]:
statdescriptive(chiffre_affaires)

{'min': 3000, 'max': 10000, 'somme': 30000, 'moyenne': 6000.0}

In [234]:
# possibilite de faire ceci from mon_module import statdescriptive, somme_element lorsque on veut importer les deux modules

### modules externes

exemple de structure : www.https://docs.python.org/fr/3/tutorial/modules.html

ensemble des modules: https://docs.python.org/3/py-modindex.html

In [235]:
# exemple utilisation de math

In [236]:
import math

In [237]:
print("Ecar-type:", math.sqrt(4))
print("Cosinus:", math.cos(90))
print("Exponentiel:", math.exp(90))

Ecar-type: 2.0
Cosinus: -0.4480736161291701
Exponentiel: 1.2204032943178408e+39


In [239]:
# exemple d'utilisation des modules statistiques
import statistics as st

In [241]:
st.mean([30, 40, 50])
st.mode([30, 40, 50])

30

In [244]:
# exemple d'utilisation de random (choice, seed, sample, randint, shuffle)
import random

In [247]:
## liste avec un certain nombre de prenoms et on choisit un des prenoms au hasard
# choisir un element aleatoire dans une liste (liste de nom)

liste_nom= ["A", "B", "C", "D", "E", "F", "G"]
random.choice(liste_nom)

'A'

In [248]:
liste_nom= ["A", "B", "C", "D", "E", "F", "G"]
random.choice(liste_nom)

'F'

In [251]:
# creer une ou des echantillons a partir de la liste
random.sample(liste_nom, 3)

['G', 'B', 'C']

In [250]:
# fixer la graine (seed) # on fixe la graine pour controler l'alea
# On fixe la graine
random.seed(3333445)
# choisr un element aleatoire dans une liste
liste_nom= ["A", "B", "C", "D", "E", "F", "G"]
random.choice(liste_nom)

'B'

In [252]:
# aleatoire float (random.random) permet generer des sorties aleatoires entre 0 et 1
random.random()

0.7886954452021958

In [253]:
# aleatoire integer
random.randint(1,100)

99

In [254]:
# melanger aleatoirement des données dans une liste (shuffle)
random.shuffle(liste_nom) # tres utile en deep learning
liste_nom

['E', 'G', 'A', 'F', 'B', 'C', 'D']

# les packages en python

Trouver les packages disponibles ici: https://pypi.org/
lien our en savoir plus
https://packaging.python.org/en/latest/tutorials/packaging-projects/)

### utilisation de mon package

In [ ]:
# installer un package
import monpackage.module as md

# deuxieme possibilité

from monpackage import module

In [ ]:
# pour avoir liste des packages disponibles

!pip list

In [ ]:
# pour installer un package
!pip install dash # le package dash pour faire les data visualistions
# pour innstaller le package dash (dask losqu'on travaille sur un groupe de données, flask pour les API,
# seaborn pour faire des graphique de qualité)

In [ ]:
# importer un package une fois qu'on l'a installé
import numpy as np

## Open 

In [257]:
# Ecrire dansle fichier et créer le fichier (premiere approche)

In [258]:
f=open("resultat.txt", "w")
f.write("Bonjour")
f.close()

In [259]:
f = open("resultat.txt", "r")
f.read()

'Bonjour'

In [262]:
# lecture en premiere approche
with open("resultat.txt", "w") as f:
    for i in range(0,10):
        f.write(f"la valeur est {i}\n") # \n pour mettre de l'espace dans ma sortie
        

In [263]:
# lecture deuxieme approche (readlines et read().splitlines())
with open("resultat.txt", "r") as f:
    resultat = f.readlines()
resultat

['la valeur est 0\n',
 'la valeur est 1\n',
 'la valeur est 2\n',
 'la valeur est 3\n',
 'la valeur est 4\n',
 'la valeur est 5\n',
 'la valeur est 6\n',
 'la valeur est 7\n',
 'la valeur est 8\n',
 'la valeur est 9\n']

# apprentissage de Numpy

### Bien demarrer avec une dimension (create)

In [265]:
# importation
import numpy as np

In [266]:
# creation d'un nd array a une dimension partir d'une liste
tableau_dim1 = np.array([33, 4, 4, 5, 6,4])
tableau_dim1

array([33,  4,  4,  5,  6,  4])

In [267]:
tableau_dim1.shape

(6,)

In [268]:
tableau_dim1.size

6

## Creer un numpy array a partir des fonctions integrées 

In [269]:
# tableau avec des zeros (np.zeros)
np.zeros??
tableau_zero = np.zeros((2,2))
tableau_zero

array([[0., 0.],
       [0., 0.]])

In [272]:
# tableau avec des uns (np.ones)
tableau_one = np.ones((2,2)) # creer une matrice avec des 1 partout
tableau_one

array([[1., 1.],
       [1., 1.]])

In [275]:
# creer une matrice identité avec np.eye()
tableau_eye = np.eye(3) # 
tableau_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [277]:
# creer un numpy array avec la fonction arrange: pour creer des nombres entre le minimum et le maximum avec un pas

np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [282]:
# creer un numpy array avec la fonction linspace # generer une sequence de nombre # tres uile pour les graphiques
# entre deux valeurs données avec un nombre de points donnés
np.linspace(0,1,50) # sors moi 50 chiffres entre 0 et 1

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## acceder aux elements, selectionner (Read)

In [283]:
# acces aux elements
tableau_dim1 = np.array([33, 4, 4, 5, 6,4])
tableau_dim1

array([33,  4,  4,  5,  6,  4])

In [ ]:
tableau_dim1[0] # pour acceder au premier élement
tableau_dim1[-1] # pour acceder au dernier element

In [ ]:
# selection des elements suivant ou qui respectent une condition
np.where(tableau_dim1>5)
nb_superieur_5 = tableau_dim1(np.where(tableau_dim1>10))