## Exemple de code monolithique

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression

In [3]:
# Chargement des données 
data = load_breast_cancer()
x, y = data['data'], data['target']

In [4]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
# Pretraitement
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [11]:
import numpy as np 
np.bincount(y) # Pour avoir une idée de la distribution des données de y, on a 212 pour la modalité 0 et 
# 357 pour la modalité 1

array([212, 357])

In [10]:
# ou bien 
import pandas as pd 
pd.DataFrame(y).value_counts()

0
1    357
0    212
Name: count, dtype: int64

In [ ]:
# Pour determiner les proportions de chaque classe
pd.DataFrame(y).value_counts(normalize=True)

0
1    0.627417
0    0.372583
Name: proportion, dtype: float64

On a 62,74 % pour la classe 1 et 37 % pour la classe 0.

Il y'a un déséquilbre de classe donc il faut mettre l'argument class_weight = 'balanced' au niveau de l'algorithme de regression logistique.

In [12]:
# Formation du modele 
clf = LogisticRegression(
    random_state=0,
    max_iter = 500,
    class_weight = 'balanced'
)

clf.fit(x, y)

LogisticRegression(class_weight='balanced', max_iter=500, random_state=0)

In [ ]:
# Score de mon modele
clf.score(x, y)

0.984182776801406

In [ ]:
# Validation croisée
from sklearn.model_selection import cross_val_score
scores = cross_val_score(
    clf,
    x,
    y,
    cv=5
)

print(scores)
print("Score moyen :", scores.mean()) # donne une estimation plus robuste et réaliste de la 
# performance du modèle qu’un simple score sur un train/test split.
print("Ecart-type :", scores.std())


[0.96491228 0.96491228 0.98245614 0.97368421 0.99115044]
Score moyen : 0.9754230709517155
Ecart-type : 0.010205795796817484


Le score de mon modele n'est pas loin du score moyen de la validation croisée, on peut donc dire que le modele va bien se généraliser sur de nouvelles données

### Interessons nous maintenant à la modularisation

On cree different fichier pout differentes taches de notre projet
Comme tache, on peut avoir l'importation des données, la division de l'ensemble de données en ensemble test train, la phase de modélisation, la phase de cross validation ou la phase de sauvegarde de modele
Pour chaque tache, on fait un fichier python, et dans ce fichier python, il peut y avoir plusieurs fichiers python selon que l'on a de sous tache dans une tache

1ere tache, faire un ficher python ou importer les données